apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: mariadb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: 1Gi   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: root
        - name: MARIADB_DATABASE
          value: employee 
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb  
  labels:
    app: mariadb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       
    app: mariadb
    tier: database
  clusterIP: None  
